# frontend/Dockerfile

# Use an official Nginx image as a parent image
FROM nginx:1.25-alpine

# Copy the static content (HTML, CSS, JS) into the Nginx web root directory
COPY . /usr/share/nginx/html

# Make port 80 available
EXPOSE 80